### ISSUE TITLE
Null relationship value error

### ISSUE THREAD

**Issue by SumarokovV** [tailflow/laravel-orion-ts#11]
When relation return `null` we have error: `Cannot convert undefined or null to object` in hydrate method

**Comment by SumarokovV** [comment]
`	public hydrate(raw: AllAttributes & Relations, response?: AxiosResponse): M {
		const model = new this.modelConstructor();

		for (const field of Object.keys(raw)) {
			const rawValue = raw[field];

			if (typeof model[field] === 'function') {
				const relationQueryBuilder: QueryBuilder<Model> = model[field]();

				if (Array.isArray(rawValue)) {
					model.$relations[field] = rawValue.map((rawRelation: Record<string, unknown>) => {
						return relationQueryBuilder.hydrate(rawRelation, response);
					});
				} else {
					if(rawValue) {
						model.$relations[field] = relationQueryBuilder.hydrate(rawValue, response);
					} else {
						model.$relations[field] = rawValue;
					}
				}
			} else {
				model.$attributes[field] = rawValue;
			}
		}

		model.$response = response;

		return model;
	}`

**Comment by SumarokovV** [comment]
[PR](https://github.com/tailflow/laravel-orion-ts/pull/12)

**Comment by alexzarbn** [comment]
Hi @SumarokovV,

Thank you for bringing this up! The PR was merged and the fix is available as part of the [v2.1.2](https://github.com/tailflow/laravel-orion-ts/releases/tag/2.1.2) release.
