### ISSUE TITLE
Batch Operations Support

### ISSUE THREAD

**Issue by olragon** [tailflow/laravel-orion-ts#13]
Thank you for the great project. Do you have any plan to implement batch support?

https://tailflow.github.io/laravel-orion-docs/v2.x/guide/batch-operations.html#batch-store

**Comment by alexzarbn** [comment]
Hi @olragon,

Yes, batch operations support will be available in Typescript SDK, but I am afraid there is no specific timeline for that at the moment.

**Comment by alexzarbn** [comment]
Batch operations are now available as part of the 3.4.0 release.
