### ISSUE TITLE
Hydrate model(s) from json

### ISSUE THREAD

**Issue by fabiosussetto** [tailflow/laravel-orion-ts#16]
Hi, thanks for this amazing package!

Is it possible to create a model instance from some JSON data? We store some user-specific data in the local storage and would be nice to call say `user.projects.store({...})` w/o having to populate the user object from the API every time.

I've seen the Model class constructor takes optional attributes and relations (https://github.com/tailflow/laravel-orion-ts/blob/main/src/model.ts#L19) , but I'm not sure how that would work. Could you please let me know if this scenario is supported or if there's a better alternative?

Thanks!

**Comment by alexzarbn** [comment]
Hi @fabiosussetto,

Yes, you can simply create a new model instance and pass the attributes into the constructor:
```ts
import {User} from '../models/user';

const user = new User({ name: 'John' });
```

You can see here how models are hydrated when queried from the API: https://github.com/tailflow/laravel-orion-ts/blob/main/src/drivers/default/builders/queryBuilder.ts#L178
