### ISSUE TITLE
Error: Network Error - GET requests

### ISSUE THREAD

**Issue by rodrigotbrun** [tailflow/laravel-orion-ts#2]
Hi,

I was running into some learning with this awesome TS Sdk. And I ran into an issue regarding GET requests (find() and get()) for models.

Both requests `find()` and `get()` I'm getting an `[Error: Network Error]`.
And every other method is working fine.

After some research, I found some issues in the axios repository, saying about the `data` option for the request. When being `data: "{}"` this error should happen.

I've added a transformRequest, to test it (like some devs reported in the issue [from axios repo](https://github.com/axios/axios/issues/3192), and I was able to successfully get the data I want.. like the code below:

```js
// Orion init and set token here...

// setting data = undefined like mentioned in the issue
const cfg = Orion.getHttpClientConfig();
cfg.transformRequest = [
  (data, headers) => {
    return undefined;
  },
];
Orion.setHttpClientConfig(cfg);

// and then, my find request
 Employee.$query()
    .find('f2d827a8-6e65-4bbf-ae35-d6a14b7adc27')
    .then((employeeProfile) =>
      console.log(JSON.stringify(employeeProfile.$attributes, null, 2)),
    )
    .catch((e) => {
      console.log(e); // No error, when data=undefined in the transformRequest
    });
```

it resolves the promise, and logs the result:

```
{
  "id": "f2d827a8-6e65-4bbf-ae35-d6a14b7adc27",
  "name": "Rodrigo Brun",
  "email": "rodrigo_1234@mailinator.com",
  "companies": []
}
```

This "solves" the problem for both `find()` and `get()`. But will get some inconsistencies with other requests methods of course. But it is just a test.

My question is, is there already some work around for this? Like, sending `undefined` to `data` when using GET requests. At least until axios should fix this issue with something ?

--

My `axios": "^0.21.1",`

And I'm testing this in a react-native project, in iOS device. (not tested on the web, or Android)

Thanks.

**Comment by alexzarbn** [comment]
Hi @rodrigotbrun,

Thank you for reporting this issue!

Please see the fix in commit https://github.com/tailflow/laravel-orion-ts/commit/e3a979a01015a9a69d3f19bec3a56f31517010f7
