### ISSUE TITLE
Reactivity in Vue Project

### ISSUE THREAD

**Issue by squpshift** [tailflow/laravel-orion-ts#33]
Is it possible to make the data returned from orion-ts queries reactive in a Vue3 project? Currently if I update MyModel.$attributes.some_attribute, changes aren't picked up by reactivity in vue. I've tried wrapping instances of MyModal in reactive(MyModel) but that doesn't help. Sorry if this is more of a noob Vue reactivity question than an issue with orion-ts but just hoping to get some help!

**Comment by alexzarbn** [comment]
Hello @squpshift,

Orion does not provide any kind of reactivity, nor there are any plans on making vue-specific SDK.
