### ISSUE TITLE
[Question] How can I add interceptor to axios instance?

### ISSUE THREAD

**Issue by abdulaziz-jm** [tailflow/laravel-orion-ts#4]
I can't find a way to access axios instance, is the there anyway I can add interceptor?

**Comment by alexzarbn** [comment]
Hi @abdulaziz-jm,

I just added the ability to create Axios instances using user-provided callback. Please check the https://github.com/tailflow/laravel-orion-ts/commit/f629e52316f0177929182fb2a2ad5db8e28bad07 commit.

Example usage:
```typescript
Orion.makeHttpClientUsing(() => {
  const client = axios.create();

  client.interceptors.request.use(...);

  return client;
});
```

**Comment by abdulaziz-jm** [comment]
Awesome, thank you.
